In [1]:
# Q1. What is NumPy, and why is it important for data science?

In [2]:
'''NumPy (Numerical Python) is a powerful Python library used for numerical computing.
 It provides support for:
 large, multi-dimensional arrays, 
 Matrices, along with a collection of mathematical functions,
 Operations on these data structures.
 It is widely used in data science, machine learning, and scientific computing due to its efficiency and ease of use.'''

'NumPy (Numerical Python) is a powerful Python library used for numerical computing.\n It provides support for:\n large, multi-dimensional arrays, \n Matrices, along with a collection of mathematical functions,\n Operations on these data structures.\n It is widely used in data science, machine learning, and scientific computing due to its efficiency and ease of use.'

In [3]:
# Q2. Explain the difference between a Python list and a NumPy array.

In [4]:
'''Python lists and NumPy arrays are both used to store collections of elements,
but they have significant differences in terms of structure, functionality, and performance.
##Diffferences:

1. Data Type Support
Python List:
Can hold elements of different data types (e.g., integers, strings, floats, etc.) in the same list.
Example: [1, "hello", 3.14]
NumPy Array:
Designed to hold elements of a single data type (homogeneous). If you mix types, NumPy will upcast them to a compatible type.
Example: np.array([1, 2, 3.5]) results in an array of floats: [1.0, 2.0, 3.5].

2. Performance
Python List:
Slower because operations are implemented in Python, and it does not support vectorized operations.
Iteration over lists involves higher overhead.
NumPy Array:
Much faster for numerical computations.

3. Memory Efficiency
Python List:
Requires more memory since each element is a Python object with additional overhead.
NumPy Array:
More memory-efficient because elements are stored in a contiguous block of memory with a fixed data type.

4. Functionality
Python List:
General-purpose and flexible, but lacks built-in methods for mathematical operations.
NumPy Array:
Designed for numerical and scientific computing. Offers a rich set of functions for mathematical, statistical, and linear algebra operations.

5. Dimensionality
Python List:
Supports 1-dimensional data naturally. Multidimensional structures require nested lists, which can be cumbersome to work with.
NumPy Array:
Easily supports multi-dimensional data (1D, 2D, 3D, etc.) with efficient indexing and slicing.

6. Broadcasting
Python List:
Does not support broadcasting. Operations must be explicitly looped or matched in size.
NumPy Array:
Supports broadcasting, allowing operations on arrays of different shapes.'''

'Python lists and NumPy arrays are both used to store collections of elements,\nbut they have significant differences in terms of structure, functionality, and performance.\n##Diffferences:\n\n1. Data Type Support\nPython List:\nCan hold elements of different data types (e.g., integers, strings, floats, etc.) in the same list.\nExample: [1, "hello", 3.14]\nNumPy Array:\nDesigned to hold elements of a single data type (homogeneous). If you mix types, NumPy will upcast them to a compatible type.\nExample: np.array([1, 2, 3.5]) results in an array of floats: [1.0, 2.0, 3.5].\n\n2. Performance\nPython List:\nSlower because operations are implemented in Python, and it does not support vectorized operations.\nIteration over lists involves higher overhead.\nNumPy Array:\nMuch faster for numerical computations.\n\n3. Memory Efficiency\nPython List:\nRequires more memory since each element is a Python object with additional overhead.\nNumPy Array:\nMore memory-efficient because elements are sto

In [11]:
# Q3. How do you create a NumPy array of zeros with a specific shape?

In [12]:
import numpy as np

In [13]:
array_zeros = np.zeros(shape=(3, 3))

In [14]:
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Q4. What are the common data types in NumPy arrays?

In [19]:
'''##Data types in numpy array:
Numeric data type
Boolean data type(True or False)
String data type
DateTime data type
Object data type'''

'##Data types in numpy array:\nNumeric data type\nBoolean data type(True or False)\nString data type\nDateTime data type\nObject data type'

In [17]:
# Q5. How do you perform element-wise addition, subtraction, multiplication, and division on NumPy arrays?

In [20]:
import numpy as np

In [30]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [31]:
# Addition

In [32]:
result=array1+array2

In [33]:
print(result)

[5 7 9]


In [34]:
# Subtraction

In [35]:
result=array1-array2

In [36]:
print(result)

[-3 -3 -3]


In [37]:
# Multiplication

In [40]:
result=array1*array2

In [41]:
print(result)

[ 4 10 18]


In [42]:
# Division

In [43]:
result=array1/array2

In [44]:
print(result)

[0.25 0.4  0.5 ]


In [45]:
# Q6. Explain the concept of array slicing in NumPy.

In [46]:
#Array slicing in NumPy is a powerful feature that allows you to extract specific parts of an array

In [47]:
#Example:

In [48]:
import numpy as np


In [49]:
array = np.array([1, 2, 3, 4, 5])

In [50]:
print(array[1:3])

[2 3]


In [51]:
# Q7. How do you find the mean, median, and mode of a NumPy array?

In [52]:
#Mean

In [53]:
import numpy as np

In [54]:
array = np.array([1, 2, 3, 4, 5])

In [55]:
mean_value = np.mean(array)

In [56]:
print(mean_value)

3.0


In [58]:
##Median

In [59]:
median_value = np.median(array)

In [60]:
print(median_value)

3.0


In [61]:
#Mode

In [62]:
import numpy as np

In [63]:
from scipy import stats


In [64]:
array = np.array([1, 2, 2, 3, 3, 3])

In [65]:
mode_value = stats.mode(array)

In [67]:
print(mode_value.mode)

3


In [68]:
# Q8. What is broadcasting in NumPy, and how does it work?

In [70]:
#Broadcasting in NumPy is a powerful feature that allows to perform operations on arrays with different shapes and sizes.

In [71]:
#How works:

In [72]:
'''1. Shape Comparison: NumPy compares the shapes of the arrays involved in the operation.
2. Broadcasting Rules: NumPy applies the broadcasting rules to determine the resulting shape.
3. Element-wise Operation: The operation is performed element-wise on the broadcasted arrays.'''

'1. Shape Comparison: NumPy compares the shapes of the arrays involved in the operation.\n2. Broadcasting Rules: NumPy applies the broadcasting rules to determine the resulting shape.\n3. Element-wise Operation: The operation is performed element-wise on the broadcasted arrays.'

In [73]:
# Q9. What is Pandas, and what are its key data structures?

In [74]:
'''Pandas is a powerful open-source Python library designed for data manipulation, analysis, and exploration.
It provides easy-to-use, high-performance data structures and functions that simplify working with structured data.
Pandas is particularly useful for tasks like cleaning, transforming, and analyzing data in formats such as CSV, Excel, SQL databases, or JSON.'''

'Pandas is a powerful open-source Python library designed for data manipulation, analysis, and exploration.\nIt provides easy-to-use, high-performance data structures and functions that simplify working with structured data.\nPandas is particularly useful for tasks like cleaning, transforming, and analyzing data in formats such as CSV, Excel, SQL databases, or JSON.'

In [75]:
# Q10.How do you import data from a CSV file into a Pandas DataFrame?

In [76]:
import pandas as pd


In [78]:
#df = pd.read_csv('file_path.csv')


In [80]:
#print(df.head())


In [81]:
# Q11.How do you select specific columns or rows from a DataFrame?

In [1]:
import pandas as pd


In [2]:
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
df = pd.DataFrame(data)


In [3]:
df.iloc[0:2, [0, 2]]  # Rows 0-1, Columns A and C


A  C
0  1  7
1  2  8

In [4]:
# Q 12.Explain the difference between the loc and iloc indexers in Pandas.

In [5]:
''' Loc: Access rows and columns using labels (names).
Example:......'''

' Loc: Access rows and columns using labels (names).\nExample:......'

In [6]:
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'])

In [8]:
print(df.loc['row1'])

A    1
B    4
C    7
Name: row1, dtype: int64


In [10]:
'''iloc: Access rows and columns using integer positions.
Example:......'''

'iloc: Access rows and columns using integer positions.\nExample:......'

In [11]:
print(df.iloc[0])

A    1
B    4
C    7
Name: row1, dtype: int64


In [12]:
# Q13.How do you handle missing values (NaN) in a DataFrame?

In [13]:
# 1. Detecting Missing Values

In [14]:
df.isnull()  # Returns a DataFrame of True/False


A      B      C
row1  False  False  False
row2  False  False  False
row3  False  False  False

In [15]:
df.isnull().any().any()  # Returns True if any NaN exists


False

In [16]:
# 2. Removing Missing Values

In [17]:
df.dropna()  # Removes rows containing any NaN


A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [18]:
df.dropna(axis=1)  # Removes columns containing any NaN


A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [20]:
import pandas as pd
import numpy as np

In [21]:
# Sample DataFrame with missing values
data = {
    'A': [1, np.nan, 3],
    'B': [4, 5, np.nan],
    'C': [np.nan, 8, 9]
}

In [22]:
df = pd.DataFrame(data)

In [23]:
# Detect missing values
print(df.isnull())

       A      B      C
0  False  False   True
1   True  False  False
2  False   True  False


In [24]:
# Drop rows with NaN
df_cleaned = df.dropna()

In [1]:
# Q14.How do you filter rows in a DataFrame based on conditions?

In [2]:
import pandas as pd

# Example DataFrame
data = {'A': [1, 2, 3, 4], 'B': [10, 20, 30, 40]}
df = pd.DataFrame(data)

# Filter rows where column A > 2
filtered_df = df[df['A'] > 2]

print(filtered_df)


   A   B
2  3  30
3  4  40


In [3]:
# Q15.How do you group data in a DataFrame and perform aggregations?

In [4]:
import pandas as pd

# Example DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A'], 
        'Values': [10, 20, 15, 25, 10]}
df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum of 'Values'
grouped = df.groupby('Category')['Values'].sum()

print(grouped)


Category
A    35
B    45
Name: Values, dtype: int64


In [5]:
# Calculate multiple aggregations
grouped = df.groupby('Category')['Values'].agg(['sum', 'mean', 'count'])

print(grouped)


          sum       mean  count
Category                       
A          35  11.666667      3
B          45  22.500000      2


In [6]:
# Q16.What is the difference between concat and merge in Pandas?

In [7]:
'''1. concat:
The concat function is used to concatenate (stack) DataFrames along rows or columns.

Key Features:
Combines DataFrames along a specified axis (0 for rows, 1 for columns).
No merging logic; it simply appends DataFrames, aligning by index or columns.
Retains all data unless specified otherwise.'''

'1. concat:\nThe concat function is used to concatenate (stack) DataFrames along rows or columns.\n\nKey Features:\nCombines DataFrames along a specified axis (0 for rows, 1 for columns).\nNo merging logic; it simply appends DataFrames, aligning by index or columns.\nRetains all data unless specified otherwise.'

In [8]:
#Example

In [9]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

result = pd.concat([df1, df2], axis=0)

print(result)


   A  B
0  1  3
1  2  4
0  5  7
1  6  8


In [10]:
'''2. merge
The merge function is used to combine DataFrames based on common columns or indices, similar to SQL joins.

Key Features:
Implements join operations (inner, outer, left, right).
Combines rows by matching values in specified columns or indices.
Requires a key column(s) for merging.'''

'2. merge\nThe merge function is used to combine DataFrames based on common columns or indices, similar to SQL joins.\n\nKey Features:\nImplements join operations (inner, outer, left, right).\nCombines rows by matching values in specified columns or indices.\nRequires a key column(s) for merging.'

In [11]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Ali', 'Bilal', 'Usman']})
df2 = pd.DataFrame({'ID': [1, 3, 4], 'Score': [85, 95, 75]})

result = pd.merge(df1, df2, on='ID')

print(result)


   ID   Name  Score
0   1    Ali     85
1   3  Usman     95


In [13]:
'''Q17.You have two DataFrames with some overlapping columns.
Describe how you would perform an outer join and explain the significance of an outer join compared to an inner join'''

'Q17.You have two DataFrames with some overlapping columns.\nDescribe how you would perform an outer join and explain the significance of an outer join compared to an inner join'

In [14]:
''' To perform an outer join with two DataFrames that have overlapping columns, you would use the merge function in pandas and 
specify the how='outer' parameter.'''

" To perform an outer join with two DataFrames that have overlapping columns, you would use the merge function in pandas and \nspecify the how='outer' parameter."

In [15]:
import pandas as pd

# Example DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [3, 4, 5],
    'Score': [95, 85, 75]
})

# Perform an outer join on the 'ID' column
result = pd.merge(df1, df2, on='ID', how='outer')

print(result)


   ID     Name  Score
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie   95.0
3   4      NaN   85.0
4   5      NaN   75.0


In [17]:
'''Significance of an Outer Join:
Retains All Data: Ensures all rows from both DataFrames are included.
Handles Missing Data: Highlights missing information by using NaN where there are no matches.
Useful for Union: Combines datasets comprehensively without discarding unmatched rows.'''

'Significance of an Outer Join:\nRetains All Data: Ensures all rows from both DataFrames are included.\nHandles Missing Data: Highlights missing information by using NaN where there are no matches.\nUseful for Union: Combines datasets comprehensively without discarding unmatched rows.'

In [18]:
# Q18.Explain the concept of vectorization in NumPy. How does it improve the performance of numerical computations?

In [19]:
'''Vectorization in NumPy refers to the process of performing operations on entire arrays (or vectors) without the need for explicit loops in Python.
It allows you to apply operations element-wise to arrays directly'''

'Vectorization in NumPy refers to the process of performing operations on entire arrays (or vectors) without the need for explicit loops in Python.\nIt allows you to apply operations element-wise to arrays directly'

In [21]:
'''Vectorization Improves Performance because:
1. Eliminates Python Loops.
2. Leverages SIMD Operations.
3. Memory Efficiency.
4. Parallelism.
5. Code Simplicity.'''

'Vectorization Improves Performance because:\n1. Eliminates Python Loops.\n2. Leverages SIMD Operations.\n3. Memory Efficiency.\n4. Parallelism.\n5. Code Simplicity.'

In [22]:
''' Q19.You have a DataFrame with a column containing dates. How would you: 
(a) Convert the date column to a datetime object? 
(b) Extract the year, month,and day from the dates? 
(c) Filter the DataFrame to select data from a specific date range?'''


' Q19.You have a DataFrame with a column containing dates. How would you: \n(a) Convert the date column to a datetime object? \n(b) Extract the year, month,and day from the dates? \n(c) Filter the DataFrame to select data from a specific date range?'

In [23]:
import pandas as pd

# Example DataFrame
data = {'Date': ['2023-01-01', '2023-02-15', '2023-03-10'], 'Value': [10, 20, 30]}
df = pd.DataFrame(data)

# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

print(df)


        Date  Value
0 2023-01-01     10
1 2023-02-15     20
2 2023-03-10     30


In [24]:
# Extract year, month, and day into new columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

print(df)


        Date  Value  Year  Month  Day
0 2023-01-01     10  2023      1    1
1 2023-02-15     20  2023      2   15
2 2023-03-10     30  2023      3   10


In [25]:
# Define the date range
start_date = '2023-01-01'
end_date = '2023-02-28'

# Filter rows where 'Date' is within the range
filtered_df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]

print(filtered_df)


        Date  Value  Year  Month  Day
0 2023-01-01     10  2023      1    1
1 2023-02-15     20  2023      2   15


In [26]:
'''Q 20.Describe a scenario where you would use a GroupBy operation in Pandas,
and explain how you would perform an aggregation (e.g., calculate the
average) within each group.'''

'Q 20.Describe a scenario where you would use a GroupBy operation in Pandas,\nand explain how you would perform an aggregation (e.g., calculate the\naverage) within each group.'

In [27]:
import pandas as pd

# Sample DataFrame
data = {
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Furniture'],
    'Sales': [200, 150, 300, 100, 400]
}
df = pd.DataFrame(data)

print(df)


      Category  Sales
0  Electronics    200
1     Clothing    150
2  Electronics    300
3     Clothing    100
4    Furniture    400


In [28]:
# Group by 'Category' and calculate the average sales
average_sales = df.groupby('Category')['Sales'].mean()

print(average_sales)


Category
Clothing       125.0
Electronics    250.0
Furniture      400.0
Name: Sales, dtype: float64


In [29]:
# Add average sales for each category to the original DataFrame
df['Average_Sales'] = df.groupby('Category')['Sales'].transform('mean')

print(df)


      Category  Sales  Average_Sales
0  Electronics    200          250.0
1     Clothing    150          125.0
2  Electronics    300          250.0
3     Clothing    100          125.0
4    Furniture    400          400.0
