In [1]:
# Q1.What is Python, and why is it widely used in data science?

In [4]:
'''Python:
Python is a high-level, interpreted programming language known for its simplicity and readability.
Python is widely used in daata science due to its:
1. Ease of learning and use
2. Rich ecosystem of libraries
3. Active community support
4. Platform independence
5. Support of big data and machine learninng
6. Visualization capabilities
7. Scalability
8. Integration and versaality
9. Popularity in Academia and Industry'''

'Python:\nPython is a high-level, interpreted programming language known for its simplicity and readability.\nPython is widely used in daata science due to its:\n1. Ease of learning and use\n2. Rich ecosystem of libraries\n3. Active community support\n4. Platform independence\n5. Support of big data and machine learninng\n6. Visualization capabilities\n7. Scalability\n8. Integration and versaality\n9. Popularity in Academia and Industry'

In [5]:
# Q2.Explain the difference between a variable and a constant in Python.

In [6]:
'''1. Variable
A variable is a named storage location in memory that can hold a value, and its value can be changed during the program's execution.
2. Constant
A constant is a value that remains unchanged during the execution of the program.'''

"1. Variable\nA variable is a named storage location in memory that can hold a value, and its value can be changed during the program's execution.\n2. Constant\nA constant is a value that remains unchanged during the execution of the program."

In [7]:
# Q3.How do you create a Python dictionary, and how is it different from a list?

In [9]:
'''A Python dictionary is created using curly braces {} with key-value pairs, e.g., my_dict = {"key1": "value1", "key2": "value2"}.
It differs from a list because dictionaries store data as key-value pairs (unordered), while lists store ordered, indexed elements.
Example:
my_dict = {"name": "Alice", "age": 25, "city": "New York"}
my_list = ["Alice", 25, "New York"]'''

'A Python dictionary is created using curly braces {} with key-value pairs, e.g., my_dict = {"key1": "value1", "key2": "value2"}.\nIt differs from a list because dictionaries store data as key-value pairs (unordered), while lists store ordered, indexed elements.\nExample:\nmy_dict = {"name": "Alice", "age": 25, "city": "New York"}\nmy_list = ["Alice", 25, "New York"]'

In [10]:
# Q4.What are Python tuples, and when would you use them over lists?

In [11]:
'''A tuple is an immutable, ordered collection of elements in Python, defined using parentheses (). 
Tuples can hold a mix of data types and allow duplicate values.
Example:
my_tuple = (1, "apple", 3.14)
When to Use:
1. When you want to ensure the data cannot be changed after creation.
Example: Storing fixed configuration settings or constants:
config = ("localhost", 8080)
2. Tuples are more memory-efficient and faster than lists for read-only operations.
3. To protect data integrity by preventing accidental modification. Example: Representing days of the week:
days = ("Monday", "Tuesday", "Wednesday")
4. Tuples can be used as keys in dictionaries (because they are hashable), while lists cannot:
my_dict = {(1, 2): "Point A", (3, 4): "Point B"}
5. Functions often return tuples to provide multiple values at once. Example:
def get_coordinates():
    return (10.5, 20.7)
x, y = get_coordinates()'''


'A tuple is an immutable, ordered collection of elements in Python, defined using parentheses (). \nTuples can hold a mix of data types and allow duplicate values.\nExample:\nmy_tuple = (1, "apple", 3.14)\nWhen to Use:\n1. When you want to ensure the data cannot be changed after creation.\nExample: Storing fixed configuration settings or constants:\nconfig = ("localhost", 8080)\n2. Tuples are more memory-efficient and faster than lists for read-only operations.\n3. To protect data integrity by preventing accidental modification. Example: Representing days of the week:\ndays = ("Monday", "Tuesday", "Wednesday")\n4. Tuples can be used as keys in dictionaries (because they are hashable), while lists cannot:\nmy_dict = {(1, 2): "Point A", (3, 4): "Point B"}\n5. Functions often return tuples to provide multiple values at once. Example:\ndef get_coordinates():\n    return (10.5, 20.7)\nx, y = get_coordinates()'

In [12]:
# Q 5.Write a Python function that takes two numbers as arguments and returns their sum.

In [14]:
def add_numbers(a, b):
    """Returns the sum of two numbers."""
    return a + b

In [15]:
# Example usage:
result = add_numbers(5, 3)

In [16]:
print(result)

8


In [17]:
# Q 6.Explain the difference between axis 0 and axis 1 in NumPy.

In [18]:
 # InNumPy, the terms axis 0 and axis 1 refer to the dimensions along which operations are performed in multi-dimensional arrays.


In [22]:
'''axis 0 (Rows)
Represents the vertical dimension (rows).
Operations along axis 0 are performed column-wise.
Often referred to as the "row axis."
Example:
.....'''

'axis 0 (Rows)\nRepresents the vertical dimension (rows).\nOperations along axis 0 are performed column-wise.\nOften referred to as the "row axis."\nExample:\n.....'

In [21]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Summing along axis 0
result = np.sum(array, axis=0)
print(result)  # Output: (sum of each column)


[12 15 18]


In [24]:
'''Axis 1 (Columns)
Represents the horizontal dimension (columns).
Operations along axis 1 are performed row-wise.
Often referred to as the "column axis."
Example:.......'''

'Axis 1 (Columns)\nRepresents the horizontal dimension (columns).\nOperations along axis 1 are performed row-wise.\nOften referred to as the "column axis."\nExample:.......'

In [25]:
# Summing along axis 1
result = np.sum(array, axis=1)
print(result)  # Output: (sum of each row)


[ 6 15 24]


In [26]:
# Q7.What are some common aggregation functions in NumPy (e.g., sum, mean)? Provide examples.

In [1]:
'''NumPy is a powerful library for numerical computing in Python.
It provides several useful aggregation functions to perform operations on arrays.
Examples:....'''

'NumPy is a powerful library for numerical computing in Python.\nIt provides several useful aggregation functions to perform operations on arrays.\nExamples:....'

In [4]:
#1.Sum(np.sum)

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
print(total_sum)  # Output: 15


15


In [5]:
#2.Mean (np.mean)

In [6]:
mean_value = np.mean(arr)
print(mean_value)  # Output: 3.0


3.0


In [7]:
# Q.8.What is broadcasting in NumPy? Explain with an example.

In [8]:
'''Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes.
NumPy automatically expands the smaller array along the dimensions with size 1 or missing dimensions to match
the shape of the larger array. This process makes array operations more efficient and concise.'''

'Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes.\nNumPy automatically expands the smaller array along the dimensions with size 1 or missing dimensions to match\nthe shape of the larger array. This process makes array operations more efficient and concise.'

In [9]:
#Example: Adding a Vector to a Matrix

In [10]:
import numpy as np

# 2x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 1x3 vector
vector = np.array([1, 2, 3])

# Add the vector to each row of the matrix using broadcasting
result = matrix + vector

print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Result:\n", result)


Matrix:
 [[1 2 3]
 [4 5 6]]
Vector:
 [1 2 3]
Result:
 [[2 4 6]
 [5 7 9]]


In [11]:
# Q9.How do you create a Pandas DataFrame from a dictionary?

In [15]:
import pandas as pd


In [16]:
data = {
    'Name': ['Ali', 'Bilal', 'Anas', 'Mehmood'],
    'Age': [25, 30, 35, 40],
    'City': ['Rawalakot', 'Bagh', 'Lahore', 'Rawalpindi']
}


In [17]:
#to create dataframe from above dictionary:

In [18]:
df = pd.DataFrame(data)
print(df)


      Name  Age        City
0      Ali   25   Rawalakot
1    Bilal   30        Bagh
2     Anas   35      Lahore
3  Mehmood   40  Rawalpindi


In [19]:
# Q10.What are the key differences between a Pandas Series and a Pandas DataFrame?

In [20]:
'''Pandas Series
1.One-Dimensional:
A Series is a one-dimensional labeled array that can hold any data type (integers, strings, floating-point numbers, etc.).
2.Index:
It has an index, which is like row labels. By default, it starts from 0.
3.Single Column:
A Series represents a single column of data, meaning it has only one column.
4.Creation:
You can create a Series from a list, dictionary, or another array.'''

'Pandas Series\n1.One-Dimensional:\nA Series is a one-dimensional labeled array that can hold any data type (integers, strings, floating-point numbers, etc.).\n2.Index:\nIt has an index, which is like row labels. By default, it starts from 0.\n3.Single Column:\nA Series represents a single column of data, meaning it has only one column.\n4.Creation:\nYou can create a Series from a list, dictionary, or another array.'

In [21]:
import pandas as pd

data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [22]:
'''Pandas DataFrame:
1.Two-Dimensional:
A DataFrame is a two-dimensional labeled data structure that can hold multiple types of data. Think of it as a table with rows and columns.
2.Index and Columns:
It has both an index (row labels) and columns (column labels).
3.Multiple Columns:
A DataFrame can contain multiple columns of data, each of which can be a different data type.
4.Creation:
You can create a DataFrame from a dictionary of arrays, lists, Series, dictionaries, or another DataFrame'''

'Pandas DataFrame:\n1.Two-Dimensional:\nA DataFrame is a two-dimensional labeled data structure that can hold multiple types of data. Think of it as a table with rows and columns.\n2.Index and Columns:\nIt has both an index (row labels) and columns (column labels).\n3.Multiple Columns:\nA DataFrame can contain multiple columns of data, each of which can be a different data type.\n4.Creation:\nYou can create a DataFrame from a dictionary of arrays, lists, Series, dictionaries, or another DataFrame'

In [23]:
data = {
    'Name': ['Ali', 'Bilal', 'Anas'],
    'Age': [25, 30, 35],
    'City': ['Rawalakot', 'Bagh', 'Lahore']
}
df = pd.DataFrame(data)
print(df)


    Name  Age       City
0    Ali   25  Rawalakot
1  Bilal   30       Bagh
2   Anas   35     Lahore


In [24]:
# Q11.How do you display the first five rows of a Pandas DataFrame?

In [25]:
'''To display the first five rows of a Pandas DataFrame, we can use the .head() method. 
By default, .head() returns the first five rows, but we can specify a different number of rows if needed.'''

'To display the first five rows of a Pandas DataFrame, we can use the .head() method. \nBy default, .head() returns the first five rows, but we can specify a different number of rows if needed.'

In [26]:
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Age': [25, 30, 35, 40, 28, 33, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio']
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the first five rows
print(df.head())


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   28      Phoenix


In [27]:
# Q12.How can you rename the columns of a Pandas DataFrame?

In [28]:
#Renaming columns in a Pandas DataFrame can be done using the .rename() method or by directly setting the .columns attribute.

In [29]:
#Method 1: Using .rename()
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

# Create DataFrame
df = pd.DataFrame(data)

# Rename columns
df_renamed = df.rename(columns={'Name': 'Full Name', 'Age': 'Years', 'City': 'Location'})
print(df_renamed)


  Full Name  Years     Location
0     Alice     25     New York
1       Bob     30  Los Angeles
2   Charlie     35      Chicago


In [30]:
#Method 2: Setting .columns Attribute
# Rename all columns
df.columns = ['Full Name', 'Years', 'Location']
print(df)


  Full Name  Years     Location
0     Alice     25     New York
1       Bob     30  Los Angeles
2   Charlie     35      Chicago


In [31]:
# Q13.What is the difference between the loc and iloc indexers in Pandas? Provide examples.

In [32]:
'''The loc and iloc indexers in Pandas are used to access rows and columns of a DataFrame, 
but they have different ways of specifying what to access.'''

'The loc and iloc indexers in Pandas are used to access rows and columns of a DataFrame, \nbut they have different ways of specifying what to access.'

In [33]:
'''loc Indexer:
Label-based indexing: loc is used to access data using row and column labels.
Inclusive: When specifying ranges, the end label is included'''

'loc Indexer:\nLabel-based indexing: loc is used to access data using row and column labels.\nInclusive: When specifying ranges, the end label is included'

In [34]:
# Example:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
print(df)

# Accessing rows by label using loc
# Get the row with label 1 (i.e., the second row)
print(df.loc[1])

# Accessing a specific column by label
print(df.loc[:, 'Age'])

# Accessing a specific row and column
print(df.loc[1, 'Name'])

# Accessing a range of rows
print(df.loc[1:3])  # Rows with labels 1, 2, and 3


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object
0    25
1    30
2    35
3    40
Name: Age, dtype: int64
Bob
      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


In [35]:
'''iloc Indexer:
Integer-based indexing: iloc is used to access data using integer positions (like array indices in Python).
Exclusive: When specifying ranges, the end index is excluded.'''

'iloc Indexer:\nInteger-based indexing: iloc is used to access data using integer positions (like array indices in Python).\nExclusive: When specifying ranges, the end index is excluded.'

In [36]:
# Example:
# Accessing rows by integer position using iloc
# Get the row at index 1 (i.e., the second row)
print(df.iloc[1])

# Accessing a specific column by integer position
print(df.iloc[:, 1])  # Second column (Age)

# Accessing a specific row and column
print(df.iloc[1, 0])  # Second row, first column (Name)

# Accessing a range of rows
print(df.iloc[1:3])  # Rows at index 1 and 2


Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object
0    25
1    30
2    35
3    40
Name: Age, dtype: int64
Bob
      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [37]:
# Q14.How do you filter rows in a DataFrame based on a condition (e.g., select rows where a column is greater than a specific value)?

In [38]:
#Filtering rows in a DataFrame based on a condition is a common task in data analysis with Pandas. You can use boolean indexing to accomplish this.
#Example:
#Suppose we have a DataFrame with information about people, and we want to filter rows where the age is greater than 30.
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# Create DataFrame
df = pd.DataFrame(data)

# Filter rows where Age is greater than 30
filtered_df = df[df['Age'] > 30]

print(filtered_df)


      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston


In [39]:
# Q15.How do you calculate the sum of values in a specific column of a Pandas DataFrame?

In [40]:
#by using the .sum() method.
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate the sum of values in the 'Age' column
age_sum = df['Age'].sum()

print("Sum of ages:", age_sum)


Sum of ages: 158


In [41]:
# Q16.Explain how the groupby() function works in Pandas. Provide an example use case.

In [42]:
'''The groupby() function in Pandas is used to split the data into groups based on some criteria,
apply a function to each group independently, 
and then combine the results back together.
This is extremely useful for summarizing and aggregating data.'''

'The groupby() function in Pandas is used to split the data into groups based on some criteria,\napply a function to each group independently, \nand then combine the results back together.\nThis is extremely useful for summarizing and aggregating data.'

In [43]:
# Example:
import pandas as pd

# Sample data
data = {
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Sales': [100, 200, 150, 300, 250, 200]
}

# Create DataFrame
df = pd.DataFrame(data)

# Group by 'Product' and calculate the sum of 'Sales' for each group
grouped = df.groupby('Product')['Sales'].sum()

print(grouped)


Product
A    450
B    450
C    300
Name: Sales, dtype: int64


In [44]:
# Q17.How do you handle missing data (NaN) in a Pandas DataFrame?

In [45]:
#1. Detecting Missing Values
# use isnull() or notnull() to detect missing values in a DataFrame:

import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, None, 40],
    'City': ['New York', None, 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# Detect missing values
print(df.isnull())


    Name    Age   City
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False


In [46]:
#2. Dropping Missing Values
# remove rows or columns with missing values using dropna():

#to drop rows with any missing values:
df_cleaned = df.dropna()
print(df_cleaned)


    Name   Age      City
0  Alice  25.0  New York
3  David  40.0   Houston


In [47]:
#to drop columns with any missing values:
df_cleaned = df.dropna(axis=1)
print(df_cleaned)


      Name
0    Alice
1      Bob
2  Charlie
3    David


In [48]:
# Q18.What is the purpose of the merge() function in Pandas? How does it differ from concat()?

In [49]:
#The merge function used to combine two DataFrames based on common columns or indices, while concat fonction Concatenate along a particular axis

In [50]:
#Example merge:

import pandas as pd

# Sample data
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Age': [35, 40, 45, 50]
})

# Merge DataFrames on 'ID' column
merged_df = df1.merge(df2, on='ID', how='inner')
print(merged_df)


   ID     Name  Age
0   3  Charlie   35
1   4    David   40


In [51]:
#Example concat:

# Sample data
df3 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

df4 = pd.DataFrame({
    'ID': [5, 6, 7, 8],
    'Name': ['Eve', 'Frank', 'Grace', 'Hannah']
})

# Concatenate DataFrames vertically (axis=0)
concat_df = pd.concat([df3, df4], axis=0)
print(concat_df)


   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
0   5      Eve
1   6    Frank
2   7    Grace
3   8   Hannah


In [52]:
# Q19.How do you sort a Pandas DataFrame by a specific column?

In [53]:
#by using .sort_values() method
#Example:

import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# Create DataFrame
df = pd.DataFrame(data)

# Sort DataFrame by the 'Age' column
sorted_df = df.sort_values(by='Age')

print(sorted_df)


      Name  Age         City
0    Alice   25     New York
4      Eve   28      Phoenix
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


In [54]:
# Q20.Create a Pandas DataFrame with sample data (e.g., student names and marks) and save it as a CSV file.

In [55]:
import pandas as pd

# Sample data
data = {
    'Student': ['Ali', 'Bilal', 'Anas', 'Mehmood', 'Wali'],
    'Marks': [85, 90, 78, 88, 92]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame as CSV file
df.to_csv('student_marks.csv', index=False)

print("DataFrame saved as 'student_marks.csv'")


DataFrame saved as 'student_marks.csv'
